[workspace]
members = ["bitcoin", "hashes", "internals", "fuzz"]

[patch.crates-io.bitcoin]
path = "bitcoin"

[patch.crates-io.bitcoin_hashes]
path = "hashes"

[patch.crates-io.bitcoin-internals]
path = "internals"
